In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
data = pd.read_excel("../data/gtd_jan_june_21.xlsx", index_col=0)

In [5]:
len(data)

4960

In [3]:
countries = data["country_txt"].value_counts(True) * 100

In [4]:
countries["United States"]

0.5241935483870969

In [5]:
for column in data.columns:
    print(column)

iyear
imonth
iday
approxdate
extended
resolution
country
country_txt
region
region_txt
provstate
city
latitude
longitude
specificity
vicinity
location
summary
crit1
crit2
crit3
doubtterr
alternative
alternative_txt
multiple
success
suicide
attacktype1
attacktype1_txt
attacktype2
attacktype2_txt
attacktype3
attacktype3_txt
targtype1
targtype1_txt
targsubtype1
targsubtype1_txt
corp1
target1
natlty1
natlty1_txt
targtype2
targtype2_txt
targsubtype2
targsubtype2_txt
corp2
target2
natlty2
natlty2_txt
targtype3
targtype3_txt
targsubtype3
targsubtype3_txt
corp3
target3
natlty3
natlty3_txt
gname
gsubname
gname2
gsubname2
gname3
gsubname3
motive
guncertain1
guncertain2
guncertain3
individual
nperps
nperpcap
claimed
claimmode
claimmode_txt
claim2
claimmode2
claimmode2_txt
claim3
claimmode3
claimmode3_txt
compclaim
weaptype1
weaptype1_txt
weapsubtype1
weapsubtype1_txt
weaptype2
weaptype2_txt
weapsubtype2
weapsubtype2_txt
weaptype3
weaptype3_txt
weapsubtype3
weapsubtype3_txt
weaptype4
weaptype4_txt
weapsubtype4
weapsubtype4_txt
weapdetail
nkill
nkillus
nkillter
nwound
nwoundus
nwoundte
property
propextent
propextent_txt
propvalue
propcomment
ishostkid
nhostkid
nhostkidus
nhours
ndays
divert
kidhijcountry
ransom
ransomamt
ransomamtus
ransompaid
ransompaidus
ransomnote
hostkidoutcome
hostkidoutcome_txt
nreleased
addnotes
scite1
scite2
scite3
dbsource
INT_LOG
INT_IDEO
INT_MISC
INT_ANY
related

In [6]:
data.sample()

,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
eventid,,,,,,,,,,,,,,,,,,,,,
202101070002,2021,1,7,NaN,0,NaT,4,Afghanistan,6,South Asia,...,NaN,"""Afghan War Casualty Report: January 2021,"" NY...",NaN,NaN,START Primary Collection,0,0,0,0,NaN

In [7]:
data.shape

(4960, 134)

In [8]:
data

,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,region_txt,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
eventid,,,,,,,,,,,,,,,,,,,,,
202101010004,2021,1,1,NaN,0,NaT,60,Egypt,10,Middle East & North Africa,...,NaN,"""Egyptian officials: Roadside bombing in Sinai...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
202101010005,2021,1,1,01/01/2021,0,NaT,92,India,6,South Asia,...,NaN,"""Terror module busted, seven arrested in J&K,""...","""Militants throw grenade on CRPF,"" HT Syndicat...",NaN,START Primary Collection,-9,-9,0,-9,NaN
202101010006,2021,1,1,NaN,0,NaT,228,Yemen,10,Middle East & North Africa,...,There is doubt that this incident meets terror...,"""Civilian reportedly dies of injuries from Hou...","""UN troubled by civilian deaths in Yemen's Hud...","""Five women killed in Yemen wedding attack,"" G...",START Primary Collection,0,0,0,0,NaN
202101010009,2021,1,1,NaN,0,NaT,4,Afghanistan,6,South Asia,...,There is doubt that this incident meets terror...,"""Afghanistan- Ghor Provincial Council Member K...","""Journalist killed on 1st day of new year in A...","""Afghanistan: 2021 Begins with Assassination o...",START Primary Collection,-9,-9,0,-9,NaN
202101010024,2021,1,2,NaN,0,NaT,182,Somalia,11,Sub-Saharan Africa,...,NaN,"""Jubbaland lawmaker killed in car bomb blast,""...","""Somali lawmaker killed in a sticky bomb attac...","""Al-Shabab claims killing regional MP in south...",START Primary Collection,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202106300023,2021,6,30,NaN,0,NaT,4,Afghanistan,6,South Asia,...,NaN,"""Gunmen blow up power pylon in Parwan,"" Afghan...","""Provinces hit by blackout after power pylon d...",NaN,START Primary Collection,-9,-9,0,-9,NaN
202106300029,2021,6,30,06/30/2021,0,NaT,138,Myanmar,5,Southeast Asia,...,NaN,"""Spring Revolution Daily News for 16-30 June 2...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
202106300030,2021,6,30,NaN,1,2021-07-08,147,Nigeria,11,Sub-Saharan Africa,...,NaN,"""Boko Haram Releases Abducted Catholic Priest ...","""Kidnapped Maiduguri Catholic Priest regains f...","""ISWAP-Boko Haram Abduct Catholic Priest In Bo...",START Primary Collection,0,0,0,0,NaN
202106300038,2021,6,30,NaN,0,NaT,45,Colombia,3,South America,...,NaN,"""Two dead and one wounded after clashes betwee...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
202107020037,2021,6,30,NaN,0,NaT,138,Myanmar,5,Southeast Asia,...,There is doubt that this incident meets terror...,"""Spring Revolution Daily News for 2-7 July 202...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [15]:
bools = data.dtypes != "object"
data.columns[bools]

Index(['iyear', 'imonth', 'iday', 'extended', 'resolution', 'country',
       'region', 'latitude', 'longitude', 'specificity', 'vicinity', 'crit1',
       'crit2', 'crit3', 'doubtterr', 'alternative', 'multiple', 'success',
       'suicide', 'attacktype1', 'attacktype2', 'attacktype3', 'targtype1',
       'targsubtype1', 'natlty1', 'targtype2', 'targsubtype2', 'natlty2',
       'targtype3', 'targsubtype3', 'natlty3', 'gsubname3', 'guncertain1',
       'guncertain2', 'guncertain3', 'individual', 'nperps', 'nperpcap',
       'claimed', 'claimmode', 'claim2', 'claimmode2', 'claim3', 'claimmode3',
       'compclaim', 'weaptype1', 'weapsubtype1', 'weaptype2', 'weapsubtype2',
       'weaptype3', 'weapsubtype3', 'weaptype4', 'weaptype4_txt',
       'weapsubtype4', 'weapsubtype4_txt', 'nkill', 'nkillus', 'nkillter',
       'nwound', 'nwoundus', 'nwoundte', 'property', 'propextent', 'propvalue',
       'ishostkid', 'nhostkid', 'nhostkidus', 'nhours', 'ndays', 'ransom',
       'ransomamt', 'ransomamtus', 'ransompaid', 'ransompaidus',
       'hostkidoutcome', 'nreleased', 'INT_LOG', 'INT_IDEO', 'INT_MISC',
       'INT_ANY'],
      dtype='object')

In [29]:
test = data["nperps"] > 0

nperps
False    4400
True      560
Name: count, dtype: int64

In [22]:
data[data["suicide"] != 0]["suicide"]

eventid
202101020009    1
202101070005    1
202101080007    1
202101150011    1
202101210004    1
               ..
202106180017    1
202106210012    1
202106270014    1
202106270016    1
202106300004    1
Name: suicide, Length: 79, dtype: int64